import type { APIRoute } from "astro";
import {
  getCachedMarketData,
  getCachedRareGoodData,
  getAllCachedMarketData,
  getCacheMetadata,
  isCacheFresh,
} from "../../lib/edsmMarketCache";
import {
  getStationMarket,
  getRareGoodMarketData,
} from "../../lib/edsmMarket";

/**
 * Market data endpoint using cached EDSM data.
 * 
 * GET /api/market-data?system=<name>&station=<name>&rare=<name> - Get data for specific rare good
 * GET /api/market-data?system=<name>&station=<name> - Get all market data for station
 * GET /api/market-data?rare=<name> - Get data for rare good by name
 * GET /api/market-data - Get all cached market data
 * 
 * Returns market data from local cache file (generated by bulk fetch script).
 * Falls back to live EDSM API if cache is stale or missing.
 * 
 * Works with local file-based caching.
 */
export const prerender = false;

export const GET: APIRoute = async ({ url }) => {
  try {
    const system = url.searchParams.get("system");
    const station = url.searchParams.get("station");
    const rare = url.searchParams.get("rare");

    // Get cache metadata
    const cacheMetadata = await getCacheMetadata();
    const cacheIsFresh = await isCacheFresh();

    // If no parameters, return all cached data
    if (!system && !station && !rare) {
      const allData = await getAllCachedMarketData();
      return new Response(
        JSON.stringify({
          found: true,
          data: allData,
          metadata: cacheMetadata,
          cacheFresh: cacheIsFresh,
        }),
        {
          status: 200,
          headers: {
            "Content-Type": "application/json",
            "Cache-Control": "public, max-age=3600", // 1 hour cache
          },
        }
      );
    }

    // If rare name only, find by rare name
    if (rare && !system && !station) {
      const cachedData = await getCachedRareGoodData(rare);

      if (cachedData) {
        return new Response(
          JSON.stringify({
            found: true,
            rare,
            data: cachedData,
            metadata: cacheMetadata,
            cacheFresh: cacheIsFresh,
            source: "cache",
          }),
          {
            status: 200,
            headers: {
              "Content-Type": "application/json",
              "Cache-Control": "public, max-age=3600",
            },
          }
        );
      }

      // Not found in cache
      return new Response(
        JSON.stringify({
          found: false,
          rare,
          data: null,
          message: "Rare good not found in cache",
          metadata: cacheMetadata,
        }),
        {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    // Require system and station for other queries
    if (!system || !station) {
      return new Response(
        JSON.stringify({
          error: "System and station parameters are required (or use ?rare=<name>)",
        }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    // Try cache first
    const cachedData = await getCachedMarketData(system, station);

    // If rare specified, get specific commodity
    if (rare) {
      if (cachedData && cachedData.commodity) {
        // Check if it's the right rare good
        if (
          cachedData.rare.toLowerCase() === rare.toLowerCase() &&
          cachedData.commodity
        ) {
          return new Response(
            JSON.stringify({
              found: true,
              system,
              station,
              rare,
              data: cachedData.commodity,
              timestamp: cachedData.timestamp,
              metadata: cacheMetadata,
              cacheFresh: cacheIsFresh,
              source: "cache",
            }),
            {
              status: 200,
              headers: {
                "Content-Type": "application/json",
                "Cache-Control": "public, max-age=3600",
              },
            }
          );
        }
      }

      // Fallback to live API if cache miss or stale
      if (!cacheIsFresh) {
        const liveData = await getRareGoodMarketData(rare, system, station);
        if (liveData) {
          return new Response(
            JSON.stringify({
              found: true,
              system,
              station,
              rare,
              data: liveData,
              metadata: cacheMetadata,
              cacheFresh: false,
              source: "live",
            }),
            {
              status: 200,
              headers: {
                "Content-Type": "application/json",
                "Cache-Control": "public, max-age=300",
              },
            }
          );
        }
      }

      return new Response(
        JSON.stringify({
          found: false,
          system,
          station,
          rare,
          data: null,
          message: "Market data not available",
          metadata: cacheMetadata,
        }),
        {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    // Return station market data
    if (cachedData) {
      return new Response(
        JSON.stringify({
          found: true,
          system,
          station,
          data: cachedData,
          metadata: cacheMetadata,
          cacheFresh: cacheIsFresh,
          source: "cache",
        }),
        {
          status: 200,
          headers: {
            "Content-Type": "application/json",
            "Cache-Control": "public, max-age=3600",
          },
        }
      );
    }

    // Fallback to live API if cache miss
    if (!cacheIsFresh) {
      const liveData = await getStationMarket(system, station);
      if (liveData) {
        return new Response(
          JSON.stringify({
            found: true,
            system,
            station,
            data: liveData,
            metadata: cacheMetadata,
            cacheFresh: false,
            source: "live",
          }),
          {
            status: 200,
            headers: {
              "Content-Type": "application/json",
              "Cache-Control": "public, max-age=300",
            },
          }
        );
      }
    }

    return new Response(
      JSON.stringify({
        found: false,
        system,
        station,
        data: null,
        message: "Market data not available",
        metadata: cacheMetadata,
      }),
      {
        status: 200,
        headers: { "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error in market-data API:", error);
    return new Response(
      JSON.stringify({
        error: "Failed to fetch market data",
        details: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
};
